language: csharp
os:
- linux
dist: trusty
dotnet: 2.1.300
mono: none

script:

# let's do the restore. 
- dotnet restore

# setup the projects to have the coverlet package in test. If it doesn't have coverlet to run the code coverage during the msbuild, then you'll get no code coverage reports.  dotnet test will just run the tests without code coverage.
- find test -name *.csproj | xargs -I % dotnet add % package coverlet.msbuild

# do the tests.  Note: I had to do some workarounds to make sure dotnet test only runs on the Test Projects.  
# see https://dasmulli.blog/2018/01/20/make-dotnet-test-work-on-solution-files/ 
- dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

after_success:
#CODECOV
- bash <(curl -s https://codecov.io/bash) -v